### ISSUE TITLE
Detalhes do Marginall

### ISSUE THREAD

**Issue by EdsonConrado** [lorieri/marginall#1]
Bom dia Leo Lorieri, gostei muito do projeto e tenho muito interesse em montar dois projetos do Marginall, sendo um pra guitarra e outro para contra-baixo, gostaria de mais detalhes das etapas de montagem me de parabeniza-lo pela ótima iniciativa e execução!!!
Desde já agradeço e aguardo o retorno.

**Comment by lorieri** [comment]
Opa,
vou criar os diagramas dos que eu fiz.
vc pretende fazer do mesmo tamanho ?

**Comment by lorieri** [comment]
detalhes aqui: https://github.com/lorieri/marginall/blob/master/how-to-pt.md

**Comment by lorieri** [comment]
se preferir, veja assim: https://lorieri.github.io/marginall/how-to-pt.html
